---
- hosts: target
  tasks:
      - name: Verify if DB/APP servises are running or not
        shell: if ps -ef | grep -i apache2 | grep -v grep > /dev/null ; then echo 'Process_running' ; else echo 'process_not_running' ; fi
        ignore_errors: true
        register: proc_status_check
      - debug: msg="{{ proc_status_check.stdout }}"
      - name:  Decision point check 
        fail: 
            msg="{{ inventory_hostname }} is haveing running application , please stop first to proceed for patching"
        when: proc_status_check.stdout == "Process_running"

      - name: Current kernel version
        shell: uname -r
        register: cur_ker

      - name: initilize patch
        yum:
            name=kernel
            state=latest
        register: yum_update
      - debug: msg=" kernel has been updated "
        when: yum_update.rc == 0
      - name: check if reboot is required or not 
        shell: kernel_new=$(rpm -qa --last kernel | head -1 | awk '{print $1}' | sed 's/kernel-//g'); kernel_now=$(uname -r); if [[ $kernel_new != $kernel_now ]] ; then echo "Reboot is required"; else echo "reboot is not required"; fi
        ignore_errors: true
        register: reboot_check
      - debug: msg="{{ reboot_check.stdout }}"

      - name: reboot after patching
        shell: shutdown -r now 
        async: 1
        poll: 0

      - name: wait for system to come up 
        pause:
              minutes: 2

      - name: new kernel version
        shell: uname -r
        register: new_kernel
      - debug: msg="New Kernel version is {{ new_kernel.stdout }} and old kernel version was {{ cur_ker.stdout }}"
